### ISSUE TITLE
X-Sendfile and X-Accel-Redirect support

### ISSUE THREAD

**Issue by brodock** [schacon/grack#13]
While Ruby/Rack is fine to be an intermediary to handle permission/authentication, it's not the best tool at reading/sending files. A better solution can be to delegate it to the webserver (Apache2/Nginx), with X-Sendfile and X-Accel-Redirect HTTP responses.

You can read more about then here: 

http://wiki.nginx.org/XSendfile
https://tn123.org/mod_xsendfile/

All you have to do is craft a HTTP response code with one of the two (configurable) and append the path for the file resource and let the webserver handle the file transmission.

**Comment by dometto** [comment]
It's been a long while, but I just looked into this, before realizing that X-Sendfile probably is not compatible with the smart-http protocol. Grack wraps the git upload-pack and receive-pack commands, which just stream the data requested by the client. As far as I know, upload-pack doesn't give you the location of the pack file, so we can't craft the sendfile header. :-(

Of course, git has to read from the pack files *somewhere*, so technically it should be possible to just return an X-Sendfile line there instead of the data. But that would require implementing our own upload-pack implementation.

Or am I missing something, @brodock, @sts?

**Comment by brodock** [comment]
You are right.

I didn't knew the implementation details... so it looks like we either implement our own upload-pack or it will not work :/

As this is a very old issue, I believe that while X-Sendifile and X-Accel-Redirect still good alternatives for big chucks of data, maybe something more "non-blocking" using EventMachine could also do some serious improvements. 

I would take a look at em-proxy implementation as inspirational: https://github.com/igrigorik/em-proxy
http://pt.slideshare.net/nickblah/rubyconf-2012-custom-reverse-proxies

**Comment by dometto** [comment]
Thanks for coming back to this, @brodock :) I've never used EventMachine myself, but wouldn't most of the benefits from that already be reaped when using e.g. thin as webserver, instead of WEBrick? That wouldn't require any changes to grack I think. Or where you thinking about more specific optimizations?

**Comment by brodock** [comment]
The idea of introducing eventmachine to the IO part of the code, is to be able to do more non blocking operations, which will improve the amount of connections grack can handle.

Thin uses eventmachine already, which should be the most plug an play implementation for this specific case, but it doesn't handle blocking operations automatically, and any blocking IO you make during a request will block the main thread, see: http://stackoverflow.com/questions/19738489/does-thin-block-main-thread-when-doing-io

When you use thin and eventmachine for IO operations together, you can get the best amount of concurrency, that's even better than puma with real threads.

As a simple example, imagine you have 100 clients trying to get files, but 20 of them are requesting from a high latency connection (3G mobile). And the other 80 are on high speed fiber optic connection.

The ones on high latency will block the connection code for a lot longer than the others with fiber, and because of that, everybody will be slowed down.

In an evented environment, the IO part of the code will be resumed in a high frequency by the fibers one, and in a low frequency by the 3G mobile clients, but speed, from the perspective of server load/work, will be the same for both, or in other words, will be evenly distributed.

**Comment by brodock** [comment]
While I focused more on the clients accessing a resource (this is mostly handled by thin itself), the other important piece in the puzzle is the resource you are accessing that needs to go to the disk and do IO (git). 

While disk can be faster, slow, depending on a lot of factors, when you use evented communications, it's the same principle I've exemplified above. While your code is waiting for the chunck of data, it will be doing other tasks that are being required.

**Comment by dometto** [comment]
Thanks for the explanation. I'll have to think more about how best to implement this. One problem is that I'm trying to keep the main rack app free of platform-dependant code, so grack can also be used under jruby with the rjgit adapter. And of course jruby has different options when it comes to concurrency. So either these optimisations will have to go into the adapters, or we should limit them to making it easier for the end user to implement some kind of concurrency.

**Comment by javanthropus** [comment]
In case it helps at all, I've created a [branch](/javanthropus/grack/tree/rewrite) that addresses some of the issues raised in this discussion.  For items that are actually files, the adapters can return an object that plays well with the X-Sendfile logic if supported by the web server and works as a decent IO stream otherwise (`Grack::FileStreamer`).  For pack handling, there is another class (`Grack::IOStreamer`) that strictly streams the IO content from the source that provides it.

These are just example implementations of a simple interface, defined by Rack for response bodies, that could theoretically be implemented to play well with EM by the adapter providers.  I've not done much directly with EM myself, but maybe the logic in `IOStreamer#each` could be extended to detect when EM is available and integrate on the fly.

**Comment by dometto** [comment]
Thanks @javanthropus! I actually rather like your rewrite (will see if there is anything I can comment on later), some much needed refactoring there. I'm hesitant about whether to merge your changes back into this repo, because this is of course actually @schacon's project, and I wouldn't want to move too far away from what he did originally without his permission. Otoh, I think your rewrite is much easier to maintain, so it would make sense. :)

**Comment by javanthropus** [comment]
Great!  I'm glad you like it, and I completely understand about the hesitation to merge.  I have some other work I'm planning to add such as complete documentation and a more full featured Rakefile similar to what I've been using in my more recent gems.  Discussing the git adapter interface is also a good idea since I was pretty much working in the vacuum of the git command line and not something like the Java native git library.  That's probably best handled outside this issue though, perhaps as a separate issue.

**Comment by dometto** [comment]
@javanthropus, I've been thinking about how best to continue this project, and the original owner agreed it might be best if I just fork and start a new org for it. I'd also move the [jgit adapter](https://github.com/dometto/rjgit_grack) to the new organization. Plus I'm now a gem owner, so I can do releases on rubygems. 

I'd like to use your code as a basis for the new org if that's ok with you. You're also very welcome to join it as a co-maintainer, as I'm not very familiar yet with your rewrite. :)

**Comment by javanthropus** [comment]
That sounds great to me. I just started working on some additions to provide backward compatibility with the existing code, but we can definitely start with what is there now. I just need to add some tests for the backward compatibility functionality before we should publish the next release.

**Comment by dometto** [comment]
@javanthropus, great! I just started the new project at [grackorg/grack](https://github.com/grackorg/grack). I wanted to do this earlier, but discovered that all likely project names (grack, gitrack, etc.) are taken by (mostly inactive) users... Didn't have the creativity to come up with a better name. :)
