### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by jackbean818** [schacon/grack#2]
was giving me "invalid length sets" or "bad length character" errors when running grack on Windows.
Turns out that the pipe under service_rpc() needs to be opened with binary mode, otherwise Windows writes \r\n instead of just \n.
It works if I change it to IO.popen(command, "r+b")

**Comment by dometto** [comment]
@jackbean818, it's been ages, but thanks for the report and the proposed fix. Was wondering if you could help me out a bit.

If I change the mode [here](https://github.com/schacon/grack/blob/master/lib/git_adapter.rb#L19) to `"w+b"` I get `ERROR IOError: closed stream` on unix/OS X. Unfortunately, I don't have access to Windwos. So could you tell me:
1. Is this still an issue on Windows with the latest grack (and all the updates to git from the past years)?
2. If so, does changing the mode to `"w+b" solve the problem for you, and do the tests still pass then?

In that case, the fix is to set the filemode conditional on the operating system.
